= Rico Samples

This repository conains a set of sample applications to demonstrate how to use Rico.

It consits of two main applications, a todo-list and and example for rest security.


== How to run

First, you need to have everything compiled, so please run `mvn install` in the root directory of this samples project.
After that, please refer to one of the sub-projects README files.

== Http client

This sample shows how the http client of Rico can be used

You can find more information about the sample link:http-client[in the subdirectory].

== Metrics sample

This sample shows how Rico metrics can be used to monitor applications.

You can find more information about the sample link:metrics-sample[in the subdirectory].

== Logging sample

This sample shows how Rico can add context information to logging and store logging centralized by using the GELF format.

You can find more information about the sample link:logging-sample[in the subdirectory].

== Todo List

This sample shows some common usecases for the remoting API by providing a server based todo list that can be shared between several clients.

You can find more information about the sample link:todo-list[in the subdirectory].


== REST Security

This sample shows how the security API of Rico can be used to secure endpoints on
the server and easily login as a client.

You can find more information about the sample link:rest-security[in the subdirectory].
